crowdstock/config/routes.rb
Rails.application.routes.draw do

  resources :company
  get '/company/:company_id/guess/new', to: "guess#new"
  post '/company/:company_id/guess', to: "guess#create"
  get '/', to: "user#index"
  post '/user', to: "user#create"
  post '/user/sign_in', to: "user#sign_in"
end

crowdstock/app/models/company.rb
class Company < ActiveRecord::Base
  has_many :guesses
  has_many :users, through: :guesses
end

crowdstock/app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :user
  belongs_to :comapny
end

crowdstock/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :guesses
  has_many :companies, through: :guesses

  has_secure_password
end

crowdstock/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

crowdstock/app/controllers/company_controller.rb
require 'json'

class CompanyController < ActionController::Base
  def index
    # if session[:user_id]
      @company = Company.all
      list = {companies: @company}
      render json: list
    # else
      # redirect_to "/"
    # end
  end
  def show

    # if session[:user_id]
      company = Company.find_by(name: params[:company])
      index = company.id
      uri = URI.parse("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%20in%20(%22COF%22%2C%22YHOO%22%2C%22AAPL%22%2C%22GOOG%22%2C%22MSFT%22)&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=")
      res = Net::HTTP.get_response(uri)
      json_response = JSON.parse(res.body)

      pe = json_response["query"]["results"]["quote"][index-1]["PERatio"]
      guesses = company.guesses
      sum = 0
      guesses.each do |guess|
        p guess.pe_guess
        sum += guess.pe_guess
      end
      mean = sum/guesses.count
      info = {actual: pe, guess: mean}
    # else
      # redirect_to "/"
    # end
    render json: info
  end
end

crowdstock/app/controllers/guess_controller.rb
class GuessController < ActionController::Base
  def new
    # if session[:user_id]
    @company_id = params[:company_id]
    # else
      # redirect_to "/"
    # end
  end
  def create
    Guess.create(company_id: params[:company_id], pe_guess: params[:q])
    redirect_to "/company"
  end
end

crowdstock/app/controllers/user_controller.rb
class UserController < ActionController::Base
  def new

  end
  def create
    @user=User.new(username: params[:username], password: params[:password])
    if @user.save
      session[:user_id]=@user.id
      redirect_to '/company'
    else
      redirect_to '/'
    end
  end

  def sign_in
    user=User.find_by(username: params[:username]).try(:authenticate, params[:password])
    if user
      session[:user_id]=user.id
      redirect_to '/company'
    else
      redirect_to '/'
    end

  end
end

crowdstock/app/helpers/application_helper.rb
module ApplicationHelper
end

crowdstock/app/views/company/index.html.erb
<% @company.each do |company|%>
<%= link_to "#{company.name}", company_path(company.id) %><br>
<% end %>

crowdstock/app/views/company/show.html.erb
Actaul P/E Ratio <br>
<%= @response %> <br><br>
User Guesses <br>
<%= @mean %> <br>
<a href = "/company/<%= @company.id %>/guess/new" >
<%= button_tag "Make a Guess"%>
</a>

crowdstock/app/views/guess/new.html.erb
<%= form_tag("/company/#{@company_id}/guess", method: "post") do %>
  <%= label_tag(:q, "Guess") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Submit") %>
<% end %>

crowdstock/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdstock</title>
  <%= stylesheet_link_tag    'app', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

crowdstock/app/views/user/new.html.erb
<%= form_tag("/user", method: "post") do %>
  <%= label_tag(:q, "Username") %>
  <%= text_field_tag(:username) %>
  <%= label_tag(:q, "Pasword") %>
  <%= password_field_tag('password') %>
  <%= submit_tag("Submit") %>
<% end %>
<%= form_tag("/user/sign_in", method: "post") do %>
  <%= label_tag(:q, "Username") %>
  <%= text_field_tag(:username) %>
  <%= label_tag(:q, "Pasword") %>
  <%= password_field_tag('password') %>
  <%= submit_tag("Submit") %>
<% end %>